packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  workerd: true

# 5/21になったら消す
minimumReleaseAge: 0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
