export const apiErrorMessages = {
	ACCOUNT_IS_SUSPENDED: 'Account is suspended',
	AUTHENTICATION_FAILED: 'Authentication failed',
	BACKUP_CODE_REQUIRED: 'Backup code required',
	BUCKET_LIMIT_EXCEEDED: 'Bucket limit exceeded',
	BUCKET_NAME_ALREADY_EXISTS: 'Bucket name already exists',
	BUCKET_NAME_IS_REQUIRED: 'bucketName is required',
	BUCKET_NOT_FOUND: 'Bucket not found',
	CANNOT_CREATE_TOKEN_FOR_PUBLIC_FILE: 'Cannot create token for public file',
	CURRENT_PASSWORD_IS_REQUIRED: 'currentPassword is required',
	DAILY_UPLOAD_LIMIT_EXCEEDED: 'Daily upload limit exceeded',
	DIRECTORY_CANNOT_BE_MOVED_INTO_ITSELF: 'Directory cannot be moved into itself',
	DIRECTORY_NOT_FOUND: 'Directory not found',
	EXTERNAL_ACCOUNT_ALREADY_LINKED: 'This external account is already linked to another user',
	EXTERNAL_ACCOUNT_LINK_FAILED: 'Failed to link external account',
	FAILED_TO_FINALIZE_UPLOAD: 'Failed to finalize upload',
	FAILED_TO_RETRIEVE_FILE: 'Failed to retrieve file',
	FILE_ALREADY_EXISTS: 'File already exists',
	FILE_CONTENT_TYPE_DOES_NOT_MATCH_FILE_EXTENSION: 'File content type does not match file extension',
	FILE_ID_IS_REQUIRED: 'fileId is required',
	FILE_IS_NOT_CLOSED: 'File is not closed',
	FILE_LIMIT_EXCEEDED: 'File limit exceeded',
	FILE_NOT_FOUND: 'File not found',
	FILE_NOT_FOUND_IN_ARCHIVE: 'File not found in archive',
	FILE_NOT_FOUND_IN_STORAGE: 'File not found in storage',
	FORBIDDEN: 'Forbidden',
	GOOGLE_OAUTH_IS_NOT_CONFIGURED: 'Google OAuth is not configured',
	GOOGLE_TOKEN_IS_REQUIRED: 'googleToken is required',
	INDIEAUTH_DISCOVERY_FAILED: 'Could not discover IndieAuth authorization endpoint from the given profile URL',
	INDIEAUTH_TOKEN_IS_REQUIRED: 'indieauthToken is required',
	INTERNAL_SERVER_ERROR: 'Internal Server Error',
	INVALID_CHALLENGE_DATA: 'Invalid challenge data',
	INVALID_CREDENTIALS: 'Invalid credentials',
	INVALID_CREDENTIALS_OR_CODE: 'Invalid credentials or code',
	INVALID_DIRECTORY_PATH: 'Invalid directory path',
	INVALID_FILE_ID: 'Invalid file ID',
	INVALID_FILE_PATH: 'Invalid file path',
	INVALID_OR_EXPIRED_CHALLENGE: 'Invalid or expired challenge',
	INVALID_PASSPHRASE: 'Invalid passphrase',
	INVALID_PASSWORD: 'Invalid password',
	INVALID_PROFILE_URL: 'Invalid profile URL',
	INVALID_TOKEN: 'Invalid token',
	INVALID_UPLOAD_OFFSET_HEADER: 'Invalid Upload-Offset header',
	INVALID_USERNAME_FORMAT: 'Invalid username format',
	NO_PASSPHRASE_SET_FOR_THIS_FILE: 'No passphrase set for this file',
	ONLY_GOOGLE_ACCOUNT_REGISTRATION_IS_ALLOWED: 'Only Google account registration is allowed',
	ONLY_GOOGLE_ACCOUNT_SIGN_IN_IS_ALLOWED: 'Only Google account sign-in is allowed',
	PASSKEY_NOT_FOUND: 'Passkey not found',
	PASSPHRASE_TOO_LONG: 'passphrase is too long',
	PATH_OR_TARGETS_ARE_REQUIRED: 'path or targets are required',
	PLAN_NOT_FOUND: 'Plan not found',
	PROFILE_URL_IS_REQUIRED: 'profile_url is required',
	PUBLIC_FILES_CANNOT_CHANGE_VISIBILITY: 'Public files cannot change visibility',
	RECENT_AUTHENTICATION_REQUIRED: 'Recent authentication is required',
	REGISTRATION_IS_CLOSED: 'Registration is closed',
	SOURCE_AND_TARGET_PATHS_ARE_REQUIRED: 'sourceBucketId, targetBucketId, sourcePath and targetPath are required',
	TARGET_ALREADY_EXISTS: 'Target already exists',
	TARGET_BUCKET_SIZE_LIMIT_EXCEEDED: 'Target bucket size limit exceeded',
	THIS_MISSKEY_SERVER_IS_NOT_ALLOWED: 'This Misskey server is not allowed',
	TOKEN_IS_REQUIRED: 'token is required',
	TOKEN_NOT_FOUND: 'Token not found',
	TURNSTILE_TOKEN_IS_REQUIRED: 'turnstileToken is required',
	TURNSTILE_VERIFICATION_FAILED: 'Turnstile verification failed',
	UNAUTHORIZED: 'Unauthorized',
	USE_POST_FOR_OAUTH_SIGNUP: 'Use POST to begin OAuth signup',
	UPLOAD_EXPIRED: 'Upload expired',
	UPLOAD_HAS_NOT_BEEN_COMPLETED: 'Upload has not been completed',
	UPLOAD_OFFSET_HEADER_IS_REQUIRED: 'Upload-Offset header is required',
	UPLOAD_SESSION_NOT_INITIALIZED: 'Upload session not initialized',
	USER_ID_IS_REQUIRED: 'userId is required',
	USER_NOT_FOUND: 'User not found',
	USERNAME_ALREADY_TAKEN: 'Username already taken',
	USERNAME_ALREADY_EXISTS: 'Username already exists',
	VERIFICATION_FAILED: 'Verification failed',
} as const;

export type ApiErrorCode = keyof typeof apiErrorMessages;

export type ApiErrorResponse = {
	error: ApiErrorCode;
	message: string;
};
